services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  client-car-1:
    build: ./client-car
    depends_on:
      - mosquitto

  client-car-2:
    build: ./client-car
    depends_on:
      - mosquitto
      
  server_a:
    build: ./empresa_a
    depends_on:
      - mosquitto
    ports:
      - "8081:8081"
  