services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  client-car:
    build: ./client-car
    depends_on:
      - mosquitto
      - empresa-c # Ensure empresa-c is started before client-car
      
  empresa-a:
    build: ./server
    depends_on:
      - mosquitto
    ports:
      - "8081:8081"
    environment:
      - INSTANCE_NAME=empresa-a # Pass the instance name as an environment variable
      - PORT=8081 # Pass the port as
  
  empresa-b:
    build: ./server
    depends_on:
      - mosquitto
      - empresa-a # Ensure empresa-a is started before empresa-b
    ports:
      - "8082:8082"
    environment:
      - INSTANCE_NAME=empresa-b # Pass the instance name as an environment variable
      - PORT=8082 # Pass the port as an environment variable

  empresa-c: 
    build: ./server
    depends_on:
      - mosquitto
      - empresa-a
      - empresa-b
    ports:
      - "8083:8083"
    environment:
      - INSTANCE_NAME=empresa-c # Pass the instance name as an environment variable
      - PORT=8083 # Pass the port as
  
  empresa-d: 
    build: ./server
    depends_on:
      - mosquitto
      - empresa-c
    ports:
      - "8084:8084"
    environment:
      - INSTANCE_NAME=empresa-d # Pass the instance name as an environment variable
      - PORT=8084 # Pass the port as

  
